//product
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

export const GET_TOP_PRODUCTS_REQUEST = "GET_TOP_PRODUCTS_REQUEST"
export const GET_TOP_PRODUCTS_SUCCESS = "GET_TOP_PRODUCTS_SUCCESS"
export const GET_TOP_PRODUCTS_FAIL = "GET_TOP_PRODUCTS_FAIL"

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

//cart
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS"
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD"
export const RESET_PAYMENT_METHOD = "RESET_PAYMENT_METHOD"

//order
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST"
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS"
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL"

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL"

export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST"
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS"
export const PAY_ORDER_FAIL = "PAY_ORDER_FAIL"
export const PAY_ORDER_RESET = "PAY_ORDER_RESET"

export const DELIVER_ORDER_REQUEST = "DELIVER_ORDER_REQUEST"
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS"
export const DELIVER_ORDER_FAIL = "DELIVER_ORDER_FAIL"
export const DELIVER_ORDER_RESET = "DELIVER_ORDER_RESET"

//user
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const GET_PROFILE = "GET_PROFILE"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const PROFILE_RESET = "PROFILE_RESET"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"

//admin
export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"
export const GET_USERS_RESET = "GET_USERS_RESET"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL"
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET"

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST"
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL"
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET"

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"
